name: Build and Run

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v2

      - name: 2. Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: 3. Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Run
        run: |
          python ./main.py &
          sleep 7 # 等待应用程序启动

      - name: 5. Build
        run: |
          wget -O localhost_content.txt http://localhost:7777
          cat localhost_content.txt

      - name: 6. Check content
        run: |
          content=$(cat localhost_content.txt)
          if [[ "$content" == "OK" ]]; then
            echo "静态网站构建完成。"
          else
            echo "未知错误。"
            exit 1
          fi

      - name: 7. Push static HTML
        run: |
          git checkout -b static-html
          
          git add .
          
          # 提交更改
          git commit -m "Build static HTML"
          
          # 推送到远程仓库
          git push origin static-html